# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a561351ea642d25df8d3c7a8119081d32a83a84fcf103b36fe575101ff65bbf672f1e4c6f2577f003f8fb2947b5ef8c8391bb397f734aeff8ee8e39750bdd6b

test:
  secret_key_base: 96209882e03ebfe2606331b9d2a2188b7d0ccdd90d983f0122aa8ae363ec8fc42397c412ecc2b7f555e290423dfb9b72da9c2231d49040ceca0ce828b5bbf588

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
